import type { Metadata } from "next";
import "./globals.css";

import Providers from "./Providers";
import InnerLayout from "./InnerLayout";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import {
  DM_Sans,
  Albert_Sans,
  Instrument_Sans,
  Rethink_Sans,
  Roboto_Flex,
  Roboto_Condensed,
  Roboto,
  Public_Sans,
  Open_Sans,
  Nunito_Sans,
  Nunito,
  Fira_Sans,
  Roboto_Slab,
} from "next/font/google";

const font_family = Roboto_Flex({
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jooble-Nextjs-Nodejs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        suppressContentEditableWarning
        //className={font_family.className}
      >
        <Providers>
          <Header />
          <InnerLayout>
            {children}
            <Footer />
          </InnerLayout>
        </Providers>
      </body>
    </html>
  );
}
