import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "./Providers";
import InnerLayout from "./InnerLayout";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jooble-Next.js-Node.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <Header />
          <InnerLayout>
            {children}
            <Footer />
          </InnerLayout>
        </Providers>
      </body>
    </html>
  );
}
